[
    {
      num: { _text: '1' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138381' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '1' },
      gihoSangse: {},
      jdName: { _text: '더불어민주당' },
      name: { _text: '이재명' },
      hanjaName: { _text: '李在明' },
      gender: { _text: '남' },
      birthday: { _text: '19641222' },
      age: { _text: '57' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정당인' },
      eduId: { _text: '68' },
      edu: { _text: '중앙대학교 법학과 졸업' },
      career1: { _text: '(전) 경기도지사' },
      career2: { _text: '(전) 성남시장' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '2' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138380' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '10' },
      gihoSangse: {},
      jdName: { _text: '신자유민주연합' },
      name: { _text: '김경재' },
      hanjaName: { _text: '金景梓' },
      gender: { _text: '남' },
      birthday: { _text: '19421103' },
      age: { _text: '79' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정당인' },
      eduId: { _text: '68' },
      edu: { _text: '서울대학교 문리과대학 정치학과 졸업' },
      career1: { _text: '(전) 제15대, 16대 국회의원' },
      career2: { _text: '(전) 제16대 한국자유총연맹 총재' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '3' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138379' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '11' },
      gihoSangse: {},
      jdName: { _text: '우리공화당' },
      name: { _text: '조원진' },
      hanjaName: { _text: '趙源震' },
      gender: { _text: '남' },
      birthday: { _text: '19590107' },
      age: { _text: '63' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정당인' },
      eduId: { _text: '221' },
      edu: { _text: '영남대학교 행정대학원 졸업(행정학 석사)' },
      career1: { _text: '(현) 우리공화당 당대표' },
      career2: { _text: '(전) 제18·19·20대 국회의원(대구달서구병)' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '4' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138375' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '12' },
      gihoSangse: {},
      jdName: { _text: '진보당' },
      name: { _text: '김재연' },
      hanjaName: { _text: '金在姸' },
      gender: { _text: '여' },
      birthday: { _text: '19801030' },
      age: { _text: '41' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정당인' },
      eduId: { _text: '68' },
      edu: { _text: '한국외국어대학교 노어과 졸업' },
      career1: { _text: '(전) 19대 국회의원' },
      career2: { _text: '(현) 진보당 대표' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '5' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138531' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '13' },
      gihoSangse: {},
      jdName: { _text: '통일한국당' },
      name: { _text: '이경희' },
      hanjaName: { _text: '李京熹' },
      gender: { _text: '남' },
      birthday: { _text: '19740120' },
      age: { _text: '48' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '통일한국당 대표' },
      eduId: { _text: '221' },
      edu: { _text: '한국외국어대학교 대학원 졸업(법학박사)' },
      career1: { _text: '(전) 2002년 서울시장 후보' },
      career2: { _text: '(전) 2017년 대통령 후보' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '6' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138402' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '14' },
      gihoSangse: {},
      jdName: { _text: '한류연합당' },
      name: { _text: '김민찬' },
      hanjaName: { _text: '金旻澯' },
      gender: { _text: '남' },
      birthday: { _text: '19580204' },
      age: { _text: '64' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '한류연합당 당대표' },
      eduId: { _text: '221' },
      edu: { _text: '원광디지털대학교 자연건강학과 졸업(이학석사)' },
      career1: { _text: '(현) 월드마스터위원회 위원장' },
      career2: { _text: '(전) 제19대 대통령선거 후보' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '7' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138362' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '2' },
      gihoSangse: {},
      jdName: { _text: '국민의힘' },
      name: { _text: '윤석열' },
      hanjaName: { _text: '尹錫悅' },
      gender: { _text: '남' },
      birthday: { _text: '19601218' },
      age: { _text: '61' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정치인' },
      eduId: { _text: '221' },
      edu: { _text: '서울대학교 대학원 졸업(법학석사)' },
      career1: { _text: '(전) 제43대 검찰총장' },
      career2: { _text: '(전) 서울중앙지방검찰청 검사장' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '8' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138383' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '3' },
      gihoSangse: {},
      jdName: { _text: '정의당' },
      name: { _text: '심상정' },
      hanjaName: { _text: '沈相奵' },
      gender: { _text: '여' },
      birthday: { _text: '19590220' },
      age: { _text: '63' },
      addr: {},
      jobId: { _text: '72' },
      job: { _text: '국회의원' },
      eduId: { _text: '68' },
      edu: { _text: '서울대학교 사범대학 사회교육학과 졸업' },
      career1: { _text: '(전) 정의당 대표' },
      career2: { _text: '(현) 국회의원' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '9' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138392' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '4' },
      gihoSangse: {},
      jdName: { _text: '국민의당' },
      name: { _text: '안철수' },
      hanjaName: { _text: '安哲秀' },
      gender: { _text: '남' },
      birthday: { _text: '19620122' },
      age: { _text: '60' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정당인' },
      eduId: { _text: '221' },
      edu: { _text: '서울대학교 대학원 졸업(의학박사)' },
      career1: { _text: '(전) 19대, 20대 국회의원' },
      career2: { _text: '(현) 국민의당 당대표' },
      status: { _text: '사퇴' }
    },
    {
      num: { _text: '10' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138395' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '5' },
      gihoSangse: {},
      jdName: { _text: '기본소득당' },
      name: { _text: '오준호' },
      hanjaName: { _text: '吳準鎬' },
      gender: { _text: '남' },
      birthday: { _text: '19750620' },
      age: { _text: '46' },
      addr: {},
      jobId: { _text: '225' },
      job: { _text: '작가' },
      eduId: { _text: '68' },
      edu: { _text: '서울대학교 인문대학 국어국문학과 졸업' },
      career1: { _text: '(현) 기본소득한국네트워크 운영위원' },
      career2: { _text: '(전) 기본소득당 용혜인 국회의원 비서관' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '11' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138378' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '6' },
      gihoSangse: {},
      jdName: { _text: '국가혁명당' },
      name: { _text: '허경영' },
      hanjaName: { _text: '許京寧' },
      gender: { _text: '남' },
      birthday: { _text: '19470713' },
      age: { _text: '74' },
      addr: {},
      jobId: { _text: '225' },
      job: { _text: '강연업' },
      eduId: { _text: '68' },
      edu: { _text: '한국방송통신대학교 법학과 졸업' },
      career1: { _text: '(전) 제15대, 제17대 대통령선거 후보' },
      career2: { _text: '(현) 국가혁명당 명예대표' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '12' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138411' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '7' },
      gihoSangse: {},
      jdName: { _text: '노동당' },
      name: { _text: '이백윤' },
      hanjaName: { _text: '李百允' },
      gender: { _text: '남' },
      birthday: { _text: '19770525' },
      age: { _text: '44' },
      addr: {},
      jobId: { _text: '225' },
      job: { _text: '노동자' },
      eduId: { _text: '58' },
      edu: { _text: '미기재' },
      career1: { _text: '(전) 금속노조 동희오토사내하청지회장' },
      career2: { _text: '(현) 산업폐기물매립장감시서산시민단체연대 공동대표' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '13' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138489' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '8' },
      gihoSangse: {},
      jdName: { _text: '새누리당' },
      name: { _text: '옥은호' },
      hanjaName: { _text: '玉恩鎬' },
      gender: { _text: '남' },
      birthday: { _text: '19710710' },
      age: { _text: '50' },
      addr: {},
      jobId: { _text: '77' },
      job: { _text: '(주)아빅스 대표' },
      eduId: { _text: '221' },
      edu: { _text: '서울대학교 대학원 졸업(교육학석사)' },
      career1: { _text: '(현) (주)아빅스 대표' },
      career2: { _text: '(전) 클린선거시민행동 공동대표' },
      status: { _text: '등록' }
    },
    {
      num: { _text: '14' },
      sgId: { _text: '20220309' },
      sgTypecode: { _text: '1' },
      huboid: { _text: '100138373' },
      sggName: { _text: '대한민국' },
      sdName: { _text: '전국' },
      wiwName: {},
      giho: { _text: '9' },
      gihoSangse: {},
      jdName: { _text: '새로운물결' },
      name: { _text: '김동연' },
      hanjaName: { _text: '金東兗' },
      gender: { _text: '남' },
      birthday: { _text: '19570128' },
      age: { _text: '65' },
      addr: {},
      jobId: { _text: '75' },
      job: { _text: '정당인' },
      eduId: { _text: '221' },
      edu: { _text: '미국 미시간대학교 대학원 졸업(정책학 박사 1989.9-1993.6)' },
      career1: { _text: '(전) 아주대학교 총장' },
      career2: { _text: '(전) 대한민국 경제부총리 겸 기획재정부 장관' },
      status: { _text: '사퇴' }
    }
  ]